### ISSUE TITLE
End Approach task list

### ISSUE THREAD

**Issue by LatentArchitect** [Latent-Arcana/project-dungeon#124]
<sub><a href="https://huly.app/guest/latarch?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzUzOTUyYWQyZWY0Y2JjYzQ2ZjcxZDQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVibGF0ZW50LWxhdGFyY2gtNjcyOTkyMWEtNTQ1ODFjZWE5YS1iYzgzNGEifQ.2FoniZCx9bmZo6ISUIVLSziADpxeWeWiptzOw-iFnhs">Huly&reg;: <b>CART-123</b></a></sub>

**Comment by LatentArchitect** [comment]
- [x] heal animation from potion
- [x] buff animation from potion (same as shrine animation?)
- [x] a version of both types of beds that is "used"
- [x] Re-export the Intro "cartographer.exe" screen at a larger size if possible. If not, don't worry for now
- [x] Create a Hover and Click alternative for the drop button if you haven't already. if you have, show me them
- [x] Upload the animations you created for the map markers to Google Drive. If you have already done so, show me where. I just need the sprite sheets for these
- [x] an animation for sleeping or resting in both types of beds.

**Comment by LatentArchitect** [comment]
Hover and on click for buttons: https://www.figma.com/design/6lqnAyzyBwMEGz8Lyx2uxS/cartographer.exe?node-id=168-2163&t=P4mrz2ImawR9MuZJ-4

**Comment by LatentArchitect** [comment]
# Where to find stuff:

Here is where to find all this stuff...

## Potion Animations:

- "Project Dungeon\Visual\MAIN_ASSETS\animations\adrenaline-potion-buff-animation-Sheet.png"
- "Project Dungeon\Visual\MAIN_ASSETS\animations\speed-potion-buff-animation-Sheet.png"
- "Project Dungeon\Visual\MAIN_ASSETS\animations\stamina-potion-buff-animation-Sheet.png"
- "Project Dungeon\Visual\MAIN_ASSETS\animations\strength-potion-buff-animation.png"
- "Project Dungeon\Visual\MAIN_ASSETS\animations\unknown-buff.png" _<- this one is just in case we need another potion or something i guess_

## Beds:

- "Project Dungeon\Visual\MAIN_ASSETS\png\bed\bed-used-vertical.png"
- "Project Dungeon\Visual\MAIN_ASSETS\png\bed\bed-used-horizontal.png"
- "Project Dungeon\Visual\MAIN_ASSETS\png\bed\bed-used-tattered-hor.png"
- "Project Dungeon\Visual\MAIN_ASSETS\png\bed\bed-used-tattered-vert.png"

## Main Screen Export:

- "Project Dungeon\Visual\MAIN_ASSETS\start-screen-export.png"

## Hover / On-Click 'Drop' Button:

https://www.figma.com/design/6lqnAyzyBwMEGz8Lyx2uxS/cartographer.exe?node-id=168-2163&t=P4mrz2ImawR9MuZJ-4

## Sleep Animation:

- "Project Dungeon\Visual\MAIN_ASSETS\animations\sleeping-animation.gif"
- "Project Dungeon\Visual\MAIN_ASSETS\animations\sleeping-animation.png"

> [!NOTE]
> My idea was just to show this for a second in place of the image for the player-charecter

---

Should be all set.
