### ISSUE TITLE
Tile Set - 16 Bit Update

### ISSUE THREAD

**Issue by LatentArchitect** [Latent-Arcana/project-dungeon#54]
# MAIN TILE-SET

Need to create a new updated tile-set that is 16x16

## TASKS

- [x] working floor tile
  [floor-tile-1.ase]
  [floor-tile-1.png]
- [ ] in-game wall tile-set
- [ ] map wall tile-set

---

# FOOTNOTE

## Current Asset List 24-09-03

[battle-axe.ase]
[battle-axe.png]
[bookshelf-1.ase]
[bookshelf-1.png]
[bugbear-DRAFT.ase]
[bugbear-DRAFT.png]
[falchion.ase]
[falchion.png]
[floor-tile-1.ase]
[floor-tile-1.png]
[geometry-pattern-1.ase]
[geometry-pattern-1.png]
[pattern-1.ase]
[pattern-1.png]
[pattern-2.ase]
[pattern-2.png]
[pattern-3.ase]
[pattern-3.png]
[player-character-v1.png]
[player-character-v2.png]
[player-character-with_dir_]lighting.ase
[player-direction-down.ase]
[player-direction-down.png]
[player-direction-left.ase]
[player-direction-left.png]
[player-direction-right.ase]
[player-direction-right.png]
[player-direction-up.ase]
[player-direction-up.png]
[potion-health-1.ase]
[potion-health-1.png]
[potion-set.ase]
[potion-set.png]
[proto.ase]
[rapier.ase]
[rapier.png]
[scraps-1.ase]
[scraps-1.png]
[scraps.ase]
[scraps.png]
[skeleton.ase]
[skeleton.png]
[sprite-bundle-2.ase]
[sprite-bundle.ase]
[table-1.ase]
[table-1.png]
[table-2.ase]
[table-2.png]
[trap-1-WIP.ase]
[trap-1-WIP.png]
